---
- name: Create the slurm.conf file
  template: dest={{ SLURM_CONF }} src=slurm.conf.j2
  notify: reload slurm control

- hostname:
    name: "{{ slurm_server_name }}"

- name: Copy the service files
  become: true
  copy:
    src: slurmctld.service
    dest: /etc/systemd/system/slurmctld.service
    owner: slurm
    group: slurm
    mode: u+rw,g-wx,o-wx

#systemctl enable slurmctld
#systemctl start slurmctld

# start SLURM daemon
- name: Start SLURM controld daemon service
  become: true
  # become_user: slurm
  # command: slurmctld
  systemd:
    name: slurmctld
    state: started
    enabled: yes

- name: Ensure slurmd is not running in front node
  shell: pgrep slurmd && killall slurmd
  ignore_errors: yes

- name: Wait Slurm daemon to be up
  wait_for:
    host: "{{slurm_server_ip}}"
    port: 6817

- name: allow the slurm user to acces the slurm logs
  file: path=/tmp/slurmctld.log mode=0644

- name: Reconfigure SLURM
  become: true
  become_user: slurm
  command: scontrol reconfigure

