---
- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0777"  # danger zone, but okay for throwaway deployments | was 0775
  with_items:
  - "{{ gluster_brick_dir }}"
  - "{{ gluster_mount_dir }}"

- name: Check if Gluster volumes already exist.
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info

- name: Connect to Gluster peers.
  shell: "gluster peer probe {{ item }}"
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  failed_when: false
  with_items: groups.all
  when: "'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Create Gluster volume.
  shell: "gluster volume create {{ gluster_brick_name }} transport tcp {{ groups['cluster_masters'][0] }}:{{ gluster_brick_dir }} force"
  register: gluster_volume_create
  changed_when: "'successful' in gluster_volume_create.stdout"
  when: "inventory_hostname == groups['cluster_masters'][0] and 'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Ensure Gluster volume is started.
  shell: "gluster volume start {{ gluster_brick_name }}"
  register: gluster_volume_start
  changed_when: "'successful' in gluster_volume_start.stdout"
  when: "inventory_hostname == groups['cluster_masters'][0] and 'Volume Name: gluster' not in gluster_volume_info.stdout"

- name: Ensure the Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ groups['cluster_masters'][0] }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted

# - name: Configure Gluster volume.
#   gluster_volume:
#     state: present
#     force: yes
#     name: "{{ gluster_brick_name }}"
#     brick: "{{ gluster_brick_dir }}"
#     #replicas: 3
#     cluster: "{{ groups.all | join(',') }}"
#     host: "{{ ansible_hostname }}"
#   run_once: true

# - name: Ensure Gluster volume is mounted.
#   mount:
#     name: "{{ gluster_mount_dir }}"
#     src: "{{ ansible_hostname }}:/{{ gluster_brick_name }}"
#     fstype: glusterfs
#     opts: "defaults,_netdev"
#     state: mounted
...